### ISSUE TITLE
question about the Cov

### ISSUE THREAD

**Issue by liyihang005** [dinhhuy2109/python-cope#2]
what is the meaning of sigmaRa, sigmata, sigmaRb, sigmatb,how to get the values of them ?

**Comment by dinhhuy2109** [comment]
Please refer to the original paper https://ieeexplore.ieee.org/abstract/document/8440786
In Section Experiments, we have explained how to obtain these matrices in a real system.

**Comment by liyihang005** [comment]
Thanks for the quick reply.The method , adding noise to A_i and B_i, is  explained in Section II-B"Representation of rigid-body transformations and of their uncertainties" of the original paper.  In Section Experiments, formula(57-60)  explained how to obtain these matrices, but covariance
matrices sigmata, sigmaRb are not diagonal matrices in the example.It dosen't matter?

**Comment by dinhhuy2109** [comment]
The inputs required are the covariances of t_a, t_b, R_a, R_b.
And it doesn't matter if these covariance matrices are diagonal or not.
